### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-touch-events#1]
# Current API

```elm
-- Touch module
type TouchEvent
    = TouchStart
    | TouchMove
    | TouchEnd
    | TouchCancel
type alias Touch =
    { clientX : Float
    , clientY : Float
    }
preventAndStop : Html.Events.Options

-- SingleTouch module
type alias SingleTouch = { ... }
onSingleTouch : Touch.TouchEvent -> Options -> (SingleTouch -> msg) -> Html.Attribute msg

-- MultiTouch module
type alias MultiTouch = { ... }
onMultiTouch : Touch.TouchEvent -> Options -> (MultiTouch -> msg) -> Html.Attribute msg
```
A lot of words are redundant there like `SingleTouch.onSingleTouch`. The Touch.Touch type is also not very explicit about the data it holds, which really are coordinates. Regarding the onXTouch functions, the TouchEvent parameter makes function calls longer and implies a `case of` pattern matching inside the function definition. Yet avoiding branching in programs is often a good idea. The Options parameter should also be optional. In my use-cases, I always wanted to prevent default and stop propagation, to have a better control of the event.

To use this api, you end up doing things like this:
```elm
dragAttributes =
    let
        onTouch touchEvent pointToMsg =
            SingleTouch.onSingleTouch touchEvent Touch.preventAndStop .touch
                |> Attributes.map (touchToPoint >> pointToMsg)
    in
        [ onTouch TouchStart StartRotatingAt
        , onTouch TouchMove PointerMovedTo
        , onTouch TouchEnd (always StopRotating)
        , onTouch TouchCancel (always StopRotating)
        ]
```

# New API

In consequence of the previous remarks, I'm thinking of a new API with the following shape:

```elm
-- Touch module ########################

type Type
    = Start
    | Move
    | End
    | Cancel

type alias Coordinates =
    { clientX : Float
    , clientY : Float
    }


-- Touch.Single module #################


type alias Event =
    { type_ : Touch.Type
    , coordinates : Touch.Coordinates
    }

onStart : (Event -> msg) -> Attribute msg
onMove : (Event -> msg) -> Attribute msg
onEnd : (Event -> msg) -> Attribute msg
onCancel : (Event -> msg) -> Attribute msg

onStartWith : Options -> (Event -> msg) -> Attribute msg
onMoveWith : Options -> (Event -> msg) -> Attribute msg
onEndWith : Options -> (Event -> msg) -> Attribute msg
onCancelWith : Options -> (Event -> msg) -> Attribute msg


-- Touch.Multi module ##################


type alias Event =
    { type_ : Touch.Type
    , changedTouches : Dict Int Touch.Coordinates
    , targetTouches : Dict Int Touch.Coordinates
    , touches : Dict Int Touch.Coordinates
    }

onStart : (Event -> msg) -> Attribute msg
onMove : (Event -> msg) -> Attribute msg
onEnd : (Event -> msg) -> Attribute msg
onCancel : (Event -> msg) -> Attribute msg

onStartWith : Options -> (Event -> msg) -> Attribute msg
onMoveWith : Options -> (Event -> msg) -> Attribute msg
onEndWith : Options -> (Event -> msg) -> Attribute msg
onCancelWith : Options -> (Event -> msg) -> Attribute msg
```

# Stricter new API

If we go further in the simplification, we can get rid of the `type_` attribute in the `Event` type. The only reason to keep it would be to enable the process of the event with the same msg. But as I said before, this implies a branching in the code and increases cyclomatic complexity. So it would look like this:

```elm
-- Touch module ########################

type alias Coordinates =
    { clientX : Float
    , clientY : Float
    }


-- Touch.Single module #################


type alias Event =
    Touch.Coordinates

onStart : (Event -> msg) -> Attribute msg
onMove : (Event -> msg) -> Attribute msg
onEnd : (Event -> msg) -> Attribute msg
onCancel : (Event -> msg) -> Attribute msg


-- Touch.Multi module ##################


type alias Event =
    { changedTouches : Dict Int Touch.Coordinates
    , targetTouches : Dict Int Touch.Coordinates
    , touches : Dict Int Touch.Coordinates
    }

onStart : (Event -> msg) -> Attribute msg
onMove : (Event -> msg) -> Attribute msg
onEnd : (Event -> msg) -> Attribute msg
onCancel : (Event -> msg) -> Attribute msg
```

With this stricter new api, you would end up doing the same example like this:
```elm
dragAttributes =
        [ Touch.Single.onStart (touchToPoint >> StartRotatingAt)
        , Touch.Single.onMove (touchToPoint >> PointerMovedTo)
        , Touch.Single.onEnd (always StopRotating)
        , Touch.Single.onCancel (always StopRotating)
        ]
```
This is much cleaner in my opinion.

**Comment by ianmackenzie** [comment]
I like the stricter new API! It definitely seemed a bit odd to me that I was being informed about what type of event I was getting when I specifically subscribed to a particular type. The user can always add their own tagging to different event types if they want (and they then have the flexibility to do things like apply the same tag to both 'end' and 'cancel' events if that makes sense).

What would you think of a flat module structure - `Touch`, `SingleTouch` and `MultiTouch`? I personally think `SingleTouch.onStart` reads a bit better than `Touch.Single.onStart`.

I'm also not sure you need a separate `Event` type alias in `SingleTouch` - I think the following reads just fine and involves one less level of mental indirection:

```elm
onStart : (Touch.Coordinates -> msg) -> Attribute msg
onMove : (Touch.Coordinates -> msg) -> Attribute msg
onEnd : (Touch.Coordinates -> msg) -> Attribute msg
onCancel : (Touch.Coordinates -> msg) -> Attribute msg
```

**Comment by mpizenberg** [comment]
Yep, you're right on both!

**Comment by mpizenberg** [comment]
Implemented with opaque types. See documentation of version 3.0.0 (d5c4f24) in [elm packages](http://package.elm-lang.org/packages/mpizenberg/elm-touch-events/3.0.0).

**Comment by ianmackenzie** [comment]
Looks great! The only thing that seems a bit weird to me is that with `Coordinates` being an 'opaque alias', the only (documented) thing you can do with a `Coordinates` value is call `clientPos` on it to get a tuple. To me it would make more sense to keep `Coordinates` as a public type alias and perhaps remove the `clientPos` function (or maybe rename it more simply `toTuple`?). If you think most people will want to work with tuples, you could even make `Coordinates` a type alias for a tuple instead of a record (and document that it refers to the underlying 'client' coordinates).

**Comment by mpizenberg** [comment]
The main reason is because "for now" I only expose the clientX and clientY properties of the event since it seems to be the most commonly used. In the near future, I might add their "screen" and "page" counterpart. Like this, I can change the implementation of the Coordinates type without major change. It will only consist in adding a `screenPos` and/or `pagePos` function.

One reason I think I might need at least the "page" one is because it is need to compute offset coordinates relative to the target of the event. Unfortunately, the touch api does not expose offsetX and offsetY like the mouse api does.

I hope all this will be an issue of the past when the pointer API is vastly supported by browsers, but for now, it's all we have (touch and mouse).

**Comment by ianmackenzie** [comment]
Ah, OK, makes sense. Thanks for the explanation!
