### ISSUE TITLE
Elm Can't Find MultiTouch module

### ISSUE THREAD

**Issue by brentbrinkley** [mpizenberg/elm-touch-events#5]
Hi I'm attempting to use your package in an app I'm working on but elm can't seem to find it. I used your example project in Ellie to see if it was just my system but Ellie says the same thing [https://ellie-app.com/3wN7jQp4nBka1/0](url). 

The exact error I get is `no module called MultiTouch has been imported` but it's in the import calls and has been installed in my elm packages.

**Update:** This seems to only effect the MultiTouch library the SingleTouch library seems to work just fine in Ellie

**Comment by mpizenberg** [comment]
Woops, I seem to have forgotten to change the `MultiTouch.Event` into `Touch.event` in this example. Corrected in 5fa0033. Also, I've verified that it's working in my computer and [Ellie](https://ellie-app.com/3wTRHcrHMRRa1/0) this time.
I guess this proves I should add automatic tests at least compiling some example code.
Thanks for the feedback! Don't hesitate if you have other questions. (PS: my id on the Elm slack is mattpiz)

**Comment by brentbrinkley** [comment]
Awesome thanks for the quick fix!
